apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6dbr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-6dbr@sha256:680072d5ef361b362b5fa70df8ed8eaba6f73472ab02410b69e08c63eacef2ac
        name: my-nodejs
        resources: {}
status: {}
